resources:
- name: my-project
  type: git
  source:
    branch: {{GIT_BRANCH_TEST}}
    uri: {{GITLAB_SSH_URI}}
    skip_ssl_verification: true

- name: my-timer
  type: time
  source:
    interval: 2m

jobs:
- name: klaus_test
  plan:
  - get: my-project
  - get: my-timer
  - task: klaus_test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: docker.artifactory.platform.manulife.io/gsd-java-basic
          tag: latest
      inputs:
      - name: my-project
      run:
        path: bash
        args: [./my-project/scripts/testfly.sh]
