resources:
- name: scripts
  type: git
  source:
    uri: 

jobs:
- name: klaus_test
  public: true
  plan:
  - get: scripts
  - task: test_fly
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: docker.artifactory.platform.manulife.io/concourse-enterprise-pipeline-http-api-resource}
      inputs:
      - name: scripts
      run:
        path: ./scripts/testfly.sh
