resources:
- name: my-project
  type: git
  source:
    branch: {{GIT_BRANCH_TEST}}
    uri: {{GITLAB_SSH_URI}}
    skip_ssl_verification: true

- name: my-timer
  type: time
  source:
    interval: 2m

jobs:
- name: test1
  plan:
  - get: my-project
  - put: my-timer

- name: test2
  plan:
  - get: my-timer
    passed: [test1]
    trigger: true

  - task: mytask
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: docker.artifactory.platform.manulife.io/gsd-java-basic
          tag: latest
      inputs:
      - name: my-timer
      run:
        path: bash
        args: [./my-timer/scripts/testfly.sh]
