resources:
- name: my-project
  type: git
  source:
    branch: {{GIT_BRANCH_TEST}}
    uri: {{GITLAB_SSH_URI}}
    skip_ssl_verification: true

- name: my-timer
  type: time
  source:
    location: Asia/Hong_Kong
    start: 3:00 PM
    stop: 4:00 PM
    days: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]

jobs:
- name: klaus_test
  plan:
  - get: my-timer
    trigger: true
  - get: my-project
  - task: klaus_test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: docker.artifactory.platform.manulife.io/gsd-java-basic
          tag: latest
      inputs:
      - name: my-project
      run:
        path: bash
        args: [./my-project/scripts/testfly.sh]
